# Generated by Django 5.2.14 on 2026-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='istighfar_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='qiyam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='salawat_count',
            field=models.IntegerField(default=0),
        ),
    ]
