# Generated by Django 5.1.15 on 2026-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_dailyprogress_istighfar_count_dailyprogress_qiyam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='matn_memorization',
            field=models.BooleanField(default=False),
        ),
    ]
